// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkfglhtrfoafuahckmsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZmdsaHRyZm9hZnVhaGNrbXNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzAwMDYsImV4cCI6MjA2NzY0NjAwNn0.ajUIpExKUgToBqdThqlUKfbjmmyLKzBAldJvsjfP33I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});